name: 'GitHub Actions Bot'

on:
  push:
    branches:
      - 'main'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Echo github env'
        run: echo github
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  (${{env.REPORT_DATE}})
          html_body: "<!doctype html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport'content='width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0'><meta http-equiv='X-UA-Compatible'content='ie=edge'><title>Document</title></head><body><h1>Hi guys!</h1><p style='text-indent: 2em'>您在github关注的${{github.repository}}仓库有新的commit信息：</p><p style='text-indent: 2em; color: #008800;'>主要信息：${{github.event.head_commit.message}}</p><p style='text-align: right; padding-right: 100px;'><a href='https://github.com/bigbigDreamer/hand-write-awesome'>View it on github.</a></p><p style='text-align: right; padding-right: 100px;'>书生祝好～</p></body></html>"
          to: jadeface.scholar@gmail.com
          from: 书生的手写代码系列
          content_type: text/html
